In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.4

In [2]:
n_rows = 10
n_cols = 1
cols = ('usia',)

df = pd.DataFrame(np.random.randint(1, 99, size=(n_rows, n_cols)), 
                  columns=cols)
df

   usia
0    46
1    91
2    29
3    63
4    47
5    22
6     2
7    56
8    48
9    55

In [3]:
df['kelompok_usia'] = pd.cut(df['usia'], 
                             bins=[0, 18, 65, 99], 
                             labels=['anak', 'dewasa', 'manula'])
df

   usia kelompok_usia
0    46        dewasa
1    91        manula
2    29        dewasa
3    63        dewasa
4    47        dewasa
5    22        dewasa
6     2          anak
7    56        dewasa
8    48        dewasa
9    55        dewasa