In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.4

In [2]:
n_rows = 5
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
                  columns=cols)
df

    A   B   C   D   E
0  15  19  12   1  13
1   5  19   1   5   9
2  10   1   8   1   9
3  15   9  17   7   2
4   1  14  19  13   1

In [3]:
df1 = df.copy(deep=True)
df1 = df1.drop([1, 4])
df1

    A   B   C  D   E
0  15  19  12  1  13
2  10   1   8  1   9
3  15   9  17  7   2

In [4]:
df2 = df.copy(deep=True)
df2 = df2.drop([0, 3])
df2

    A   B   C   D  E
1   5  19   1   5  9
2  10   1   8   1  9
4   1  14  19  13  1

In [5]:
df_inner = pd.merge(df1, df2, how='inner')
df_inner

    A  B  C  D  E
0  10  1  8  1  9

In [6]:
df_outer = pd.merge(df1, df2, how='outer')
df_outer

    A   B   C   D   E
0   1  14  19  13   1
1   5  19   1   5   9
2  10   1   8   1   9
3  15   9  17   7   2
4  15  19  12   1  13