In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.4

In [4]:
n_rows = 365
n_cols = 2
cols = ['col1', 'col2']

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), columns=cols)

df.index = pd.date_range(start='2024-01-01', periods=n_rows, freq='D')

print(df)

            col1  col2
2024-01-01    13     9
2024-01-02    14     8
2024-01-03    12     1
2024-01-04    17    15
2024-01-05     5    10
...          ...   ...
2024-12-26    13     2
2024-12-27     5     4
2024-12-28     5    17
2024-12-29     5    12
2024-12-30     2    10

[365 rows x 2 columns]

In [5]:
weekdays_df = df[df.index.dayofweek.isin([0, 1, 2, 3, 4])]
weekdays_df.head(7)

            col1  col2
2024-01-01    13     9
2024-01-02    14     8
2024-01-03    12     1
2024-01-04    17    15
2024-01-05     5    10
2024-01-08    19     1
2024-01-09    18     3

In [6]:
weekends_df = df[df.index.dayofweek.isin([5, 6])]
weekends_df.head(7)

            col1  col2
2024-01-06    18    14
2024-01-07     8    12
2024-01-13    12    10
2024-01-14    19    12
2024-01-20     4     9
2024-01-21    10    10
2024-01-27     7     7